# Generated by Django 5.2.6 on 2026-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_book_url_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='twitter_handle',
            field=models.URLField(blank=True, max_length=20),
        ),
    ]
