# Generated by Django 5.2.6 on 2026-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_twitter_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='twitter_handle',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
